// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.oacp.hark_platform

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is FlutterError) {
    listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

private fun createConnectionError(channelName: String): FlutterError {
  return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Generated class from Pigeon that represents data sent in messages. */
data class DiscoveredAppMessage (
  val packageName: String,
  val authority: String,
  val appLabel: String,
  val versionName: String,
  val manifestJson: String? = null,
  val contextMarkdown: String? = null,
  val error: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): DiscoveredAppMessage {
      val packageName = pigeonVar_list[0] as String
      val authority = pigeonVar_list[1] as String
      val appLabel = pigeonVar_list[2] as String
      val versionName = pigeonVar_list[3] as String
      val manifestJson = pigeonVar_list[4] as String?
      val contextMarkdown = pigeonVar_list[5] as String?
      val error = pigeonVar_list[6] as String?
      return DiscoveredAppMessage(packageName, authority, appLabel, versionName, manifestJson, contextMarkdown, error)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      packageName,
      authority,
      appLabel,
      versionName,
      manifestJson,
      contextMarkdown,
      error,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class BackupInfo (
  val path: String,
  val sizeBytes: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BackupInfo {
      val path = pigeonVar_list[0] as String
      val sizeBytes = pigeonVar_list[1] as Long
      return BackupInfo(path, sizeBytes)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      path,
      sizeBytes,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class OacpResultMessage (
  val requestId: String? = null,
  val status: String,
  val capabilityId: String? = null,
  val message: String? = null,
  val error: String? = null,
  val sourcePackage: String? = null,
  val result: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): OacpResultMessage {
      val requestId = pigeonVar_list[0] as String?
      val status = pigeonVar_list[1] as String
      val capabilityId = pigeonVar_list[2] as String?
      val message = pigeonVar_list[3] as String?
      val error = pigeonVar_list[4] as String?
      val sourcePackage = pigeonVar_list[5] as String?
      val result = pigeonVar_list[6] as String?
      return OacpResultMessage(requestId, status, capabilityId, message, error, sourcePackage, result)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      requestId,
      status,
      capabilityId,
      message,
      error,
      sourcePackage,
      result,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class OverlayChatMessage (
  val id: String,
  val role: String,
  val text: String,
  val isPending: Boolean,
  val isError: Boolean,
  val metadata: String? = null,
  val sourceAppName: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): OverlayChatMessage {
      val id = pigeonVar_list[0] as String
      val role = pigeonVar_list[1] as String
      val text = pigeonVar_list[2] as String
      val isPending = pigeonVar_list[3] as Boolean
      val isError = pigeonVar_list[4] as Boolean
      val metadata = pigeonVar_list[5] as String?
      val sourceAppName = pigeonVar_list[6] as String?
      return OverlayChatMessage(id, role, text, isPending, isError, metadata, sourceAppName)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      role,
      text,
      isPending,
      isError,
      metadata,
      sourceAppName,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class OverlayStateMessage (
  val messages: List<OverlayChatMessage>,
  val isListening: Boolean,
  val isThinking: Boolean,
  val statusText: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): OverlayStateMessage {
      val messages = pigeonVar_list[0] as List<OverlayChatMessage>
      val isListening = pigeonVar_list[1] as Boolean
      val isThinking = pigeonVar_list[2] as Boolean
      val statusText = pigeonVar_list[3] as String
      return OverlayStateMessage(messages, isListening, isThinking, statusText)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      messages,
      isListening,
      isThinking,
      statusText,
    )
  }
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DiscoveredAppMessage.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BackupInfo.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          OacpResultMessage.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          OverlayChatMessage.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          OverlayStateMessage.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is DiscoveredAppMessage -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is BackupInfo -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is OacpResultMessage -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is OverlayChatMessage -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is OverlayStateMessage -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface HarkCommonApi {
  fun isDefaultAssistant(callback: (Result<Boolean>) -> Unit)
  fun discoverOacpApps(callback: (Result<List<DiscoveredAppMessage>>) -> Unit)
  fun findBackup(fileName: String, callback: (Result<BackupInfo?>) -> Unit)
  fun saveBackup(fileName: String, callback: (Result<String>) -> Unit)
  fun restoreBackup(fileName: String, callback: (Result<String?>) -> Unit)
  fun deleteBackup(fileName: String, callback: (Result<Boolean>) -> Unit)

  companion object {
    /** The codec used by HarkCommonApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `HarkCommonApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: HarkCommonApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.hark_platform.HarkCommonApi.isDefaultAssistant$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.isDefaultAssistant{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.hark_platform.HarkCommonApi.discoverOacpApps$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.discoverOacpApps{ result: Result<List<DiscoveredAppMessage>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.hark_platform.HarkCommonApi.findBackup$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val fileNameArg = args[0] as String
            api.findBackup(fileNameArg) { result: Result<BackupInfo?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.hark_platform.HarkCommonApi.saveBackup$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val fileNameArg = args[0] as String
            api.saveBackup(fileNameArg) { result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.hark_platform.HarkCommonApi.restoreBackup$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val fileNameArg = args[0] as String
            api.restoreBackup(fileNameArg) { result: Result<String?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.hark_platform.HarkCommonApi.deleteBackup$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val fileNameArg = args[0] as String
            api.deleteBackup(fileNameArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface HarkOverlayApi {
  fun dismiss()
  fun openFullApp()
  fun micPressed()
  fun cancelListening()

  companion object {
    /** The codec used by HarkOverlayApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `HarkOverlayApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: HarkOverlayApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.hark_platform.HarkOverlayApi.dismiss$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.dismiss()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.hark_platform.HarkOverlayApi.openFullApp$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.openFullApp()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.hark_platform.HarkOverlayApi.micPressed$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.micPressed()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.hark_platform.HarkOverlayApi.cancelListening$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.cancelListening()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface HarkOverlayBridgeApi {
  fun pushStateToOverlay(state: OverlayStateMessage)
  fun notifyOverlayActive(active: Boolean)

  companion object {
    /** The codec used by HarkOverlayBridgeApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `HarkOverlayBridgeApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: HarkOverlayBridgeApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.hark_platform.HarkOverlayBridgeApi.pushStateToOverlay$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val stateArg = args[0] as OverlayStateMessage
            val wrapped: List<Any?> = try {
              api.pushStateToOverlay(stateArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.hark_platform.HarkOverlayBridgeApi.notifyOverlayActive$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val activeArg = args[0] as Boolean
            val wrapped: List<Any?> = try {
              api.notifyOverlayActive(activeArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface HarkMainApi {
  fun openAssistantSettings()

  companion object {
    /** The codec used by HarkMainApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `HarkMainApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: HarkMainApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.hark_platform.HarkMainApi.openAssistantSettings$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.openAssistantSettings()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class HarkOverlayFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by HarkOverlayFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
  }
  fun onNewSession(sessionIdArg: String, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.hark_platform.HarkOverlayFlutterApi.onNewSession$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(sessionIdArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  fun onStateUpdate(stateArg: OverlayStateMessage, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.hark_platform.HarkOverlayFlutterApi.onStateUpdate$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(stateArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class HarkMainFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by HarkMainFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
  }
  fun onOverlayMicPressed(callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.hark_platform.HarkMainFlutterApi.onOverlayMicPressed$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(null) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  fun onOverlayCancelListening(callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.hark_platform.HarkMainFlutterApi.onOverlayCancelListening$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(null) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  fun onOverlayOpened(callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.hark_platform.HarkMainFlutterApi.onOverlayOpened$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(null) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  fun onOverlayDismissed(callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.hark_platform.HarkMainFlutterApi.onOverlayDismissed$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(null) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class HarkResultFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by HarkResultFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
  }
  fun onOacpResult(resultArg: OacpResultMessage, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.hark_platform.HarkResultFlutterApi.onOacpResult$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(resultArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
}
